[tool.poetry]
name = "xarray-cube"
version = "0.1.0"
description = "xarray extension for spectral cube analysis"
authors = [
    "Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>",
    "Rin Yamada <yamada@a.phys.nagoya-u.ac.jp>",
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/a-lab-nagoya/xarray-cube/"
documentation = "https://a-lab-nagoya.github.io/xarray-cube/"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^20.8b"
flake8 = "^3.8"
ipython = "^7.16"
ipykernel = "^5.3"
pydata-sphinx-theme = "^0.4"
pytest = "^6.0"
sphinx = "^3.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
